"""
Saudi Vision 2030 Mega Projects Database
Curated intelligence on major development projects.
"""
import pandas as pd


def get_megaprojects_data() -> pd.DataFrame:
    """Return comprehensive Vision 2030 mega-projects database."""
    
    projects = [
        {
            "name": "NEOM - The Line",
            "developer": "NEOM Company (PIF)",
            "sector": "Smart City / Mixed-Use",
            "region": "Tabuk (Northwest)",
            "estimated_value_usd": 500000000000,
            "status": "Under Construction",
            "completion_year": 2039,
            "description": "170km linear city with zero cars, zero streets, and zero carbon emissions. Vertical construction of 500m-tall mirrored structures housing 9 million residents.",
            "opportunity_sectors": "Construction, MEP, Smart Systems, AI/IoT, Transport, Healthcare, Education, Renewable Energy, Hospitality",
            "website": "https://www.neom.com/en-us/regions/theline",
            "key_stats": "170km length | 9M residents | Zero carbon | Mirror facade",
            "phase": "Phase 1 (2025-2030)",
        },
        {
            "name": "NEOM - Oxagon",
            "developer": "NEOM Company (PIF)",
            "sector": "Industrial / Port / Manufacturing",
            "region": "Tabuk (Northwest)",
            "estimated_value_usd": 50000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "World's largest floating industrial complex and advanced manufacturing hub, featuring the region's first fully automated port.",
            "opportunity_sectors": "Manufacturing, Logistics, Port Operations, Automation, Robotics, Clean Energy, Hydrogen, Supply Chain",
            "website": "https://www.neom.com/en-us/regions/oxagon",
            "key_stats": "Floating city | Automated port | Advanced manufacturing | Green hydrogen",
            "phase": "Phase 1 (2025-2028)",
        },
        {
            "name": "NEOM - Trojena",
            "developer": "NEOM Company (PIF)",
            "sector": "Tourism / Sports",
            "region": "Tabuk (Northwest)",
            "estimated_value_usd": 30000000000,
            "status": "Under Construction",
            "completion_year": 2028,
            "description": "Mountain tourism destination featuring year-round outdoor skiing, adventure sports, and a nature reserve. Host of 2029 Asian Winter Games.",
            "opportunity_sectors": "Sports Infrastructure, Hospitality, Mountain Tourism, Ski Systems, F&B, Event Management",
            "website": "https://www.neom.com/en-us/regions/trojena",
            "key_stats": "2029 Asian Winter Games | Year-round skiing | 10,000+ jobs | Nature reserve",
            "phase": "Phase 1 (2025-2028)",
        },
        {
            "name": "NEOM - Sindalah",
            "developer": "NEOM Company (PIF)",
            "sector": "Luxury Tourism",
            "region": "Tabuk (Northwest)",
            "estimated_value_usd": 5000000000,
            "status": "Operational",
            "completion_year": 2024,
            "description": "Ultra-luxury island resort in the Red Sea with yacht marina, premium hotels, beach clubs, and fine dining. NEOM's first operational destination.",
            "opportunity_sectors": "Hospitality Operations, Luxury Retail, Marina Services, F&B, Marine Tourism",
            "website": "https://www.neom.com/en-us/regions/sindalah",
            "key_stats": "Yacht club | 3 luxury hotels | 38 F&B outlets | Golf academy",
            "phase": "Operational",
        },
        {
            "name": "Red Sea Global - The Red Sea",
            "developer": "Red Sea Global (PIF)",
            "sector": "Luxury Eco-Tourism",
            "region": "Tabuk / Madinah",
            "estimated_value_usd": 16000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "Luxury regenerative tourism destination across 90+ islands and 200km of coastline. 50+ hotels, international airport, and marine conservation program.",
            "opportunity_sectors": "Hospitality, Construction, Marine Engineering, Environmental, Aviation, Renewable Energy, IT Infrastructure",
            "website": "https://www.redseaglobal.com",
            "key_stats": "90+ islands | 50+ hotels | 200km coastline | 75% land preserved",
            "phase": "Phase 1 (Shura Island open) / Phase 2 (2026-2030)",
        },
        {
            "name": "Red Sea Global - Amaala",
            "developer": "Red Sea Global (PIF)",
            "sector": "Ultra-Luxury Tourism / Wellness",
            "region": "Tabuk",
            "estimated_value_usd": 10000000000,
            "status": "Under Construction",
            "completion_year": 2028,
            "description": "Ultra-luxury wellness and arts destination, the 'Riviera of the Middle East', with 8 hotels, Yacht Club, Marine Life Institute, and Triple Bay development.",
            "opportunity_sectors": "Luxury Hospitality, Wellness, Arts & Culture, Marine Biology, Yacht Services, Premium F&B",
            "website": "https://www.redseaglobal.com/en/destinations/amaala",
            "key_stats": "8 hotels Phase 1 | Yacht Club | Marine Institute | Art galleries",
            "phase": "Phase 1 (2025-2028)",
        },
        {
            "name": "Diriyah Gate",
            "developer": "Diriyah Gate Development Authority (PIF)",
            "sector": "Heritage / Culture / Tourism",
            "region": "Riyadh",
            "estimated_value_usd": 63000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "14 sq km heritage and cultural district surrounding the UNESCO World Heritage site of At-Turaif. Features luxury hotels, museums, retail, and F&B precincts.",
            "opportunity_sectors": "Heritage Conservation, Luxury Hospitality, Museum Design, Smart City, Retail, F&B, Landscape Architecture",
            "website": "https://www.diriyah.sa",
            "key_stats": "14 sq km | UNESCO at-Turaif | 38 hotels | 20 museums | 100+ restaurants",
            "phase": "Phase 1 (2025-2027)",
        },
        {
            "name": "Qiddiya",
            "developer": "Qiddiya Investment Company (PIF)",
            "sector": "Entertainment / Sports / Culture",
            "region": "Riyadh",
            "estimated_value_usd": 8000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "Capital of entertainment, sports, and culture. Features Six Flags theme park, speed park, motorsport facilities, water park, and golf courses across 367 sq km.",
            "opportunity_sectors": "Theme Park Engineering, Sports Infrastructure, Entertainment Tech, Hospitality, F&B, Automotive, Events",
            "website": "https://qiddiya.com",
            "key_stats": "367 sq km | Six Flags | Speed Park | Motorsport | Water Park | Golf",
            "phase": "Phase 1 (Six Flags 2026)",
        },
        {
            "name": "ROSHN",
            "developer": "ROSHN Group (PIF)",
            "sector": "Residential / Urban Development",
            "region": "Multiple (Riyadh, Jeddah, Eastern)",
            "estimated_value_usd": 22000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "Saudi Arabia's largest national community developer. Building integrated communities with homes, schools, parks, hospitals, and retail across major cities.",
            "opportunity_sectors": "Residential Construction, Community Infrastructure, Schools, Healthcare, Parks, Retail, Smart Home Tech",
            "website": "https://roshn.sa",
            "key_stats": "100M+ sqm developed | SEDRA Riyadh | ALAROUS Jeddah | WAREFA Eastern | 100K+ homes",
            "phase": "Multiple phases across cities",
        },
        {
            "name": "King Abdullah Financial District (KAFD)",
            "developer": "KAFD Development Management",
            "sector": "Financial / Commercial",
            "region": "Riyadh",
            "estimated_value_usd": 10000000000,
            "status": "Partially Operational",
            "completion_year": 2026,
            "description": "World-class financial district in Riyadh with 59 towers, conference center, and luxury retail. Central business hub for regional HQ program companies.",
            "opportunity_sectors": "Commercial Fit-Out, Finance, Corporate Services, Premium Retail, F&B, Smart Building Systems",
            "website": "https://kafd.sa",
            "key_stats": "1.6M sqm | 59 towers | 68 restaurants | Conference center | Transit hub",
            "phase": "Operational / Final Phase",
        },
        {
            "name": "King Salman Park",
            "developer": "Royal Commission for Riyadh City",
            "sector": "Urban Green Space / Culture",
            "region": "Riyadh",
            "estimated_value_usd": 23000000000,
            "status": "Under Construction",
            "completion_year": 2027,
            "description": "One of the world's largest urban parks (13.4 sq km) on the old Riyadh airport site. Features Royal Arts Complex, sports facilities, water features, and 12M sqm green space.",
            "opportunity_sectors": "Landscape Architecture, Cultural Venues, Sports, Irrigation, Smart Parks, Environmental, Horticulture",
            "website": "https://kingsalmanpark.sa",
            "key_stats": "13.4 sq km | Royal Arts Complex | 12M sqm green | 7.5km wadi | Sports hub",
            "phase": "Phase 1 (2025-2027)",
        },
        {
            "name": "Sports Boulevard",
            "developer": "Royal Commission for Riyadh City",
            "sector": "Sports / Urban Infrastructure",
            "region": "Riyadh",
            "estimated_value_usd": 5000000000,
            "status": "Under Construction",
            "completion_year": 2027,
            "description": "135km walking and cycling boulevard connecting Riyadh neighborhoods with sports facilities, green corridors, and community spaces.",
            "opportunity_sectors": "Urban Design, Sports Infrastructure, Landscape, Cycling Systems, Smart Lighting, Community Facilities",
            "website": "https://sportsboulevard.sa",
            "key_stats": "135km length | Wadi Hanifah connection | Sports venues | Green corridors",
            "phase": "Phase 1 (2025-2027)",
        },
        {
            "name": "Riyadh Season / Boulevard City",
            "developer": "General Entertainment Authority",
            "sector": "Entertainment / Events",
            "region": "Riyadh",
            "estimated_value_usd": 4000000000,
            "status": "Operational / Expanding",
            "completion_year": 2027,
            "description": "Year-round entertainment district with theme parks, concert venues, immersive experiences, and international brand attractions. Boulevard World features 7 themed zones.",
            "opportunity_sectors": "Entertainment Tech, Events, AV Systems, F&B, Hospitality, Ticketing, Marketing, IP Licensing",
            "website": "https://riyadhseason.sa",
            "key_stats": "15M+ visitors 2024 | Boulevard World | Winter Wonderland | Combat Field",
            "phase": "Annual + Permanent venues",
        },
        {
            "name": "Jeddah Central (Tower & District)",
            "developer": "Jeddah Central Development Company",
            "sector": "Mixed-Use / Supertall",
            "region": "Jeddah",
            "estimated_value_usd": 20000000000,
            "status": "Under Construction",
            "completion_year": 2032,
            "description": "Master-planned waterfront district with the iconic 2km+ supertall tower, opera house, museum, stadium, aquarium, oceanarium, and mixed-use development on 5.7M sqm.",
            "opportunity_sectors": "Supertall Engineering, Marine Construction, Cultural Venues, Hospitality, Stadium Design, Smart City",
            "website": "https://jeddahcentral.sa",
            "key_stats": "5.7M sqm | 2km+ tower | Opera | Stadium | Marina | Aquarium",
            "phase": "Phase 1 Infrastructure (2024-2028)",
        },
        {
            "name": "AlUla",
            "developer": "Royal Commission for AlUla",
            "sector": "Heritage Tourism / Culture",
            "region": "Madinah",
            "estimated_value_usd": 15000000000,
            "status": "Under Construction",
            "completion_year": 2035,
            "description": "Transformation of the ancient Nabataean heritage site into a world-class cultural tourism destination with Aman and Banyan Tree resorts, museums, and adventure tourism.",
            "opportunity_sectors": "Heritage Conservation, Luxury Hospitality, Museum Design, Adventure Tourism, Archaeology, Eco-Tourism",
            "website": "https://experiencealula.com",
            "key_stats": "Hegra UNESCO site | Sharaan Resort (Jean Nouvel) | Aman/Banyan Tree | Maraya concert hall",
            "phase": "Phase 1 (2025-2028)",
        },
        {
            "name": "Riyadh Metro",
            "developer": "Royal Commission for Riyadh City",
            "sector": "Transport / Infrastructure",
            "region": "Riyadh",
            "estimated_value_usd": 23000000000,
            "status": "Partially Operational",
            "completion_year": 2026,
            "description": "6-line, 176km automated metro system with 85 stations. One of the world's largest public transport projects, transforming mobility in the capital.",
            "opportunity_sectors": "Rail Operations, Station Retail, Transit-Oriented Development, Maintenance, Ticketing, Digital Systems",
            "website": "https://riyadhmetro.sa",
            "key_stats": "6 lines | 176km | 85 stations | Driverless | 3.6M daily riders capacity",
            "phase": "Phased opening (2024-2026)",
        },
        {
            "name": "Saudi Entertainment Ventures (SEVEN)",
            "developer": "SEVEN / PIF",
            "sector": "Entertainment / Leisure",
            "region": "Multiple",
            "estimated_value_usd": 12000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "Developing 21 entertainment destinations across 14 Saudi cities with theme parks, waterparks, cinemas, bowling, and family entertainment centers.",
            "opportunity_sectors": "Theme Park Design, FEC Operations, Waterpark Engineering, Cinema, F&B, Arcade/Gaming, Events",
            "website": "https://seven.sa",
            "key_stats": "21 destinations | 14 cities | 150+ attractions | Family entertainment",
            "phase": "Multiple cities rolling out",
        },
        {
            "name": "The Rig",
            "developer": "Public Investment Fund",
            "sector": "Tourism / Entertainment",
            "region": "Arabian Gulf",
            "estimated_value_usd": 5000000000,
            "status": "Planning / Design",
            "completion_year": 2030,
            "description": "World-first offshore tourism platform inspired by oil rig aesthetics. Features extreme sports, amusement park, hospitality, and diving experiences in the Arabian Gulf.",
            "opportunity_sectors": "Offshore Engineering, Marine Construction, Extreme Sports, Hospitality, Diving/Marine Recreation",
            "website": "https://therig.sa",
            "key_stats": "Offshore platform | Extreme sports | Diving | Hotels | 3 linked platforms",
            "phase": "Design Phase",
        },
        {
            "name": "New Murabba",
            "developer": "New Murabba Development Company (PIF)",
            "sector": "Mixed-Use / Iconic Architecture",
            "region": "Riyadh",
            "estimated_value_usd": 50000000000,
            "status": "Under Construction",
            "completion_year": 2030,
            "description": "Downtown Riyadh development featuring The Mukaab — a 400m cubic landmark building — alongside commercial, residential, hospitality, and cultural facilities across 19 sq km.",
            "opportunity_sectors": "Iconic Architecture, Mixed-Use Development, Retail, Hospitality, Smart Building, Cultural Venues",
            "website": "https://newmurabba.com",
            "key_stats": "19 sq km | The Mukaab (400m cube) | 104,000 residential | 9,000 hotel rooms | Immersive tech",
            "phase": "Phase 1 (2025-2030)",
        },
    ]
    
    df = pd.DataFrame(projects)
    df["estimated_value_usd"] = df["estimated_value_usd"].astype(float)
    df["estimated_value_sar"] = df["estimated_value_usd"] * 3.75  # SAR conversion
    
    return df


def get_megaprojects_summary(df: pd.DataFrame) -> dict:
    """Generate mega-projects summary statistics."""
    active = df[df["status"] != "Completed"]
    return {
        "total_projects": len(df),
        "active_projects": len(active),
        "total_value_usd": active["estimated_value_usd"].sum(),
        "total_value_sar": active["estimated_value_sar"].sum(),
        "by_sector": df["sector"].value_counts().to_dict(),
        "by_region": df["region"].value_counts().to_dict(),
        "by_status": df["status"].value_counts().to_dict(),
        "avg_completion": int(df["completion_year"].mean()),
    }


def get_opportunity_sectors(df: pd.DataFrame) -> dict:
    """Extract and count all opportunity sectors across projects."""
    sector_counts = {}
    for _, row in df.iterrows():
        sectors = [s.strip() for s in row["opportunity_sectors"].split(",")]
        for sector in sectors:
            sector_counts[sector] = sector_counts.get(sector, 0) + 1
    return dict(sorted(sector_counts.items(), key=lambda x: x[1], reverse=True))
